apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: jenkins
