apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minio
  name: minio-deployment
  labels:
    app: minio
    deployment: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args: 
            - minio server /data --console-address :9090
          env:
            - name: MINIO_SERVER_URL
              value: MINIO_SERVER_URL
            - name: MINIO_ROOT_USER
              vallue: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              value: MINIO_ROOT_PASSWORD
            - name: MINIO_BROWSER_REDIRECT_URL
              value: MINIO_BROWSER_REDIRECT_URL
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"

          volumeMounts:
          - name: minio-data
            mountPath: /data
      volumes:
        - name: minio-data
          emptyDir:
