apiVersion: v1
kind: Service
metadata:
  namespace: minio
  name: minio-service
  labels:
    service: minio

spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090